name: tests

on: [push, pull_request]

jobs:
  tests:
      name: tests
      runs-on: ubuntu-latest
      steps:
        - name: Checkout file123
          uses: actions/checkout@v2
        - uses: actions/setup-node@v2
          with:
            node-version: '18'
        - name: cypress install
          run: cypress install
          
        - name: Run tests
          uses: cypress-io/github-action@v5
          env:
              BROWSERSTACK_USERNAME: ${{ secrets.BROWSERSTACK_USERNAME }}
              BROWSERSTACK_ACCESS_KEY: ${{ secrets. BROWSERSTACK_ACCESS_KEY }}
          with:
              install: true
              working-directory: .
              command: yarn bstack --local true --local-mode always-on --local-identifier cy-bstack-${{github.run_id}}-${{github.run_attempt}}
