name: tests

on: [push, pull_request]

jobs:
  tests:
      name: tests
      runs-on: ubuntu-latest
      steps:

        - name: Checkout file
          uses: actions/checkout@v2
        - uses: actions/setup-node@v2
          with:
            node-version: '18'

        - name: 'BrowserStack Env Setup'  # Invokes the setup-env action
          uses: browserstack/github-actions/setup-env@master
          with:
            username:  ${{ secrets.BROWSERSTACK_USERNAME }}
            access-key: ${{ secrets. BROWSERSTACK_ACCESS_KEY }}
            install: true
            working-directory: .
            command: npm install -g browserstack-cypress-cli && yarn bstack --local true --local-mode always-on --local-identifier cy-bstack-${{github.run_id}}-${{github.run_attempt}}
  
