name: tests

on: [push, pull_request]

jobs:
  tests:
      name: tests
      runs-on: ubuntu-latest
      steps:

        - name: 'BrowserStack Env Setup'  # Invokes the setup-env action
          uses: browserstack/github-actions/setup-env@master
          with:
            username:  ${{ secrets.BROWSERSTACK_USERNAME }}
            access-key: ${{ secrets. BROWSERSTACK_ACCESS_KEY }}
        
        - name: Checkout file123
          uses: actions/checkout@v2
        - uses: actions/setup-node@v2
          with:
            node-version: '18'
        - name: 'Building web application to be tested'
          run: npm install

        - name: 'Installing browserstack-cypress-cli'
          run: npm install -g browserstack-cypress-cli

        - name: 'Running test on BrowserStack with local testing enabled'  # Invokes the actual test script that would run on BrowserStack browsers
          run:  BROWSERSTACK_LOCAL=true yarn bstack --local true --local-mode always-on --local-identifier cy-bstack-${{github.run_id}}-${{github.run_attempt}}
          
